services:
  server:
    build: .
    image: ilunity/foody-nest:latest
    restart: always
    volumes:
      - static:/usr/src/app/dist/static
    environment:
      - DB_DIALECT
      - DB_HOST=postgres
      - DB_PORT
      - DB_USERNAME
      - DB_PASSWORD
      - DB_NAME
      - PORT
      - JWT_SECRET
      - SMTP_HOST
      - SMTP_PORT
      - SMTP_USER
      - SMTP_PASS
      - CLIENT_HOST
      - STATIC_FOLDER

    depends_on:
      - postgres
    ports:
      - ${PORT}:${PORT}

  postgres:
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}

volumes:
  pgdata:
    driver: local
  static:
    driver: local
