name: Publish docker image

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB_DIALECT: ${{ secrets.DB_DIALECT }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      PORT: ${{ secrets.PORT }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      SMTP_HOST: ${{ secrets.SMTP_HOST }}
      SMTP_PORT: ${{ secrets.SMTP_PORT }}
      SMTP_USER: ${{ secrets.SMTP_USER }}
      SMTP_PASS: ${{ secrets.SMTP_PASS }}
      CLIENT_HOST: ${{ secrets.CLIENT_HOST }}
      STATIC_FOLDER: ${{ secrets.STATIC_FOLDER }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build docker compose
        run: docker compose build

      - name: Push images to DO Container Registry
        run: docker compose push

      - name: Executing remote ssh commands to set env
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo DB_PORT=${{ secrets.DB_PORT }} >> ${{ secrets.secrets.PROJECT_FOLDER }}/.env
            echo DB_DIALECT=${{ secrets.DB_DIALECT }} >> ${{ secrets.secrets.PROJECT_FOLDER }}/.env
            echo DB_USERNAME=${{ secrets.DB_USERNAME }} >> ${{ secrets.secrets.PROJECT_FOLDER }}/.env
            echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> ${{ secrets.secrets.PROJECT_FOLDER }}/.env
            echo DB_NAME=${{ secrets.DB_NAME }} >> ${{ secrets.secrets.PROJECT_FOLDER }}/.env
            echo PORT=${{ secrets.PORT }} >> ${{ secrets.secrets.PROJECT_FOLDER }}/.env
            echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> ${{ secrets.secrets.PROJECT_FOLDER }}/.env
            echo SMTP_HOST=${{ secrets.SMTP_HOST }} >> ${{ secrets.secrets.PROJECT_FOLDER }}/.env
            echo SMTP_PORT=${{ secrets.SMTP_PORT }} >> ${{ secrets.secrets.PROJECT_FOLDER }}/.env
            echo SMTP_USER=${{ secrets.SMTP_USER }} >> ${{ secrets.secrets.PROJECT_FOLDER }}/.env
            echo SMTP_PASS=${{ secrets.SMTP_PASS }} >> ${{ secrets.secrets.PROJECT_FOLDER }}/.env
            echo CLIENT_HOST=${{ secrets.CLIENT_HOST }} >> ${{ secrets.secrets.PROJECT_FOLDER }}/.env
            echo STATIC_FOLDER=${{ secrets.STATIC_FOLDER }} >> ${{ secrets.secrets.PROJECT_FOLDER }}/.env

      - name: Run command on remote server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          password: ${{secrets.SSH_PASSWORD}}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo ./docker-compose.yml >> ${{ secrets.secrets.PROJECT_FOLDER }}
            docker-compose down
            docker-compose up
