name: Publish docker image

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    env:
      DB_DIALECT=${{ secrets.DB_DIALECT }}
      DB_HOST=${{ secrets.DB_HOST }}
      DB_PORT=${{ secrets.DB_PORT }}
      DB_USERNAME=${{ secrets.DB_USERNAME }}
      DB_PASSWORD=${{ secrets.DB_PASSWORD }}
      DB_NAME=${{ secrets.DB_NAME }}
      PORT=${{ secrets.PORT }}
      JWT_SECRET=${{ secrets.JWT_SECRET }}
      SMTP_HOST=${{ secrets.SMTP_HOST }}
      SMTP_PORT=${{ secrets.SMTP_PORT }}
      SMTP_USER=${{ secrets.SMTP_USER }}
      SMTP_PASS=${{ secrets.SMTP_PASS }}
      CLIENT_HOST=${{ secrets.CLIENT_HOST }}
      STATIC_FOLDER=${{ secrets.STATIC_FOLDER }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args: |
            "NEXT_PUBLIC_HOSTNAME=${{ secrets.NEXT_PUBLIC_HOSTNAME }}"
            "NEXT_PUBLIC_HOST=${{ secrets.NEXT_PUBLIC_HOST }}"
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/foody-next:latest
